version: "3"
services:
  todo-app-dev:
    build:
      context: .
    image: todo-app:dev
    container_name: todo-app-dev
    env_file:
     - ./.env
    volumes:
      - .:/home/todo/app
    ports:
      - 5001:5001 #dev port
    restart: unless-stopped
