version: "3"
services:
  todo-app-prod:
    image: todo-app:prod
    container_name: todo-app-production
    environment:
      - SECRET_KEY=secret-key
      - SECRET_APIKEY=
      - SECRET_APITOKEN=
      - BOARD_NAME=
    ports:
      - 5000:5000 #prod port
    restart: unless-stopped